openapi: 3.0.3
info:
  title: Price API
  version: 1.0.0
  description: Sample description.

servers:
  - url: https://api.jup.ag/

tags:
  - name: Price
    description: Endpoints related to Price

paths:
  /price/v2:
    get:
      tags:
      - Price
      summary: price
      description: "Returns prices of specified tokens.\n\nRefer to [Price API doc](/docs/utility/price-api) for more information."
      parameters:
      - name: ids
        in: query
        description: "- The token mint address(es) to get price(s) on\n- Comma separate to pass in multiple"
        required: true
        schema:
          type:
          - string
        example: 'So11111111111111111111111111111111111111112'
      - name: vsToken
        in: query
        description: "- A token mint address to compare the prices against\n- By default, prices are denominated by USD\n- If parameter is used with SOL mint address, denominates in the price in SOL"
        required: false
        schema:
          type:
          - string
      - name: showExtraInfo
        in: query
        description: "To use, pass in `=true`\n- Get more details such as\n  - Unix timestamp\n  - Buy price for Jupiter last swap and quote\n  - Sell price for Jupiter last swap and quote\n  - Confidence and depth information\n- Cannot use `vsToken` with this parameter"
        required: false
        schema:
          type:
            - string